# Mandatory settings

blog_theme: light # or use dark
name: Satya Borgohain
description: Musings of a polymorphic ape.
paginate: 10
url: http://syborg.dev
attribution: https://github.com/nielsenramon/chalk

# Optional settings

about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
timeline_enabled: false
research_enabled: true
project_enabled: true
art_enabled: true
discus_identifier: syborg-dev # Add your Disqus identifier
ga_analytics: UA-143745680-2 # Add your GA Tracking Id
local_fonts: true # Change to true if you wish to use local fonts
rss_enabled: true # Change to false if not
scrollappear_enabled: true # Change to false to disable
tag_nav_enabled: false # Change to true if you wish to show an additional 'tag-list' navigation below the header
tag_cloud_enabled: true
theme_toggle: false # Change to true if you wish to show an icon in the navigation for dynamic theme toggling
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: satyaborg # Add your GitHub handle
  linkedin: satyaborg # Add your LinkedIn handle
  twitter: satyaborg # Add your Twitter handle
  email: satya.borg@gmail.com # Add your Email address
  bitcoin: # Add your Bitcoin link or address
  ethereum: # Add your Ethereum link or address
  gitlab: # Add your GitLab handle
  youtube: # Add your Youtube handle
  twitch: # Add your Twitch handle
  discord: # Add you Discord server invitation ID
  tumblr: # Add your Tumblr handle
  bitbucket: # Add your Bitbucket handle
  docker: # Add your Docker Hub handle
  instagram: # Add your Instagram handle
  keybase: # Add your Keybase handle
  medium: # Add your Medium handle
  spotify: # Add your Spotify handle
  stackoverflow: # Add your Stack Overflow ID number
  steam: # Add your Steam handle


# Important settings (change at own risk)

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug
# markdown: kramdown
# kramdown:
#   math_engine: katex

